### ISSUE TITLE
US8: As a USER I want to CREATE SUB-TASK FOR ISSUE.

### ISSUE THREAD

**Issue by lubomyl** [lubomyl/JiraEX#21]
Sub-task is ordinary task with parent property.

- [x] On Issue edit page add sub-task command
- [x] Redirect followed by CREATE NEW ISSUE user story. Briefly define summary and type and create sub-task
- [x] On sub-task creation redirect to ISSUE EDIT.
